### ISSUE TITLE
Serve Static files with an HTTP server

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/centos7-s2i-web-app#6]
Since the result of the build command is just static files, we can probably serve them with a HTTP server.  Something like NGINX.

**Comment by lholmquist** [comment]
for NGINX, we could probably follow this a little bit, https://github.com/openshift/source-to-image/tree/master/examples/nginx-centos7  on installing and running it

**Comment by lholmquist** [comment]
Question:  Does this static server, need to be super optimized for serving static content.  I'm under the impression what ever we use is just for serving files in 1 pod, and there will most likely be another layer above this that does the "ops-y" stuff like setting custom domain names, load balancing, etc...

in my experiments with getting something working, i was using the serve module, https://github.com/zeit/serve

@lance thoughts?

**Comment by lance** [comment]
Honestly, I think it would make the most sense to serve static content using nginx. It's going to be orders of magnitude faster than a node app.

What about doing something like this.

* Extend `bucharestgold/centos7-s2i-nodejs`, e.g. in your `Dockerfile` you have `FROM bucharestgold/centos7-s2i-nodejs`.
* In your `Dockerfile` add the relevant bits from [here](https://github.com/openshift/source-to-image/blob/master/examples/nginx-centos7/Dockerfile#L11-L42). There will be a few changes needed, but not many.
* Make the S2I `assemble` script so that it does the Node.js build, as well as set up nginx as [here](https://github.com/openshift/source-to-image/blob/master/examples/nginx-centos7/s2i/bin/assemble). (Don't restore artifacts!) At the [end](https://github.com/openshift/source-to-image/blob/master/examples/nginx-centos7/s2i/bin/assemble#L35) just copy the output from the Node.js build to the nginx `html` directory.
* Make the S2I `run` script so that it just does the same thing as here: https://github.com/openshift/source-to-image/blob/master/examples/nginx-centos7/s2i/bin/run

This seems pretty straightforward, leverages the existing builder image, and just overlays nginx (which - especially if configured correctly, will be waaaay faster than a node server) on top of it.

**Comment by lholmquist** [comment]
Yea, thats pretty much what i was thinking in terms of flow and sort of what i have now(expect the FROM part and nginx bits)

I wasn't sure i could use our builder image in the FROM section since it is a builder image,  but then again, my docker skills are low :)

I'll play around with this more tomorrow

**Comment by lholmquist** [comment]
Should work now, 885a3017c88f38e914c77b2834e4c40950e23951
